# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "cms-combine" %}
{% set version = "10.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a6fecc8b4adc4e631425eeee7501d0258ab64ef36b24680696c2e6f8d38403e7
  folder: HiggsAnalysis/CombinedLimit

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - pip
    - python>3.9
      # on hold until https://github.com/conda-forge/root-feedstock/issues/273
    - root
    - boost-cpp
    - eigen
    - vdt

  run:
    - python
    - pandas

test:
  imports:
    - HiggsAnalysis.CombinedLimit.PhysicsModel
  commands:
    - combine -h
    - text2workspace.py -h

about:
  home: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  summary: 'A software tool used for statistical analysis within the CMS experiment'
  description: |
    Combine is a RooStats / RooFit - based software tool used for statistical analysis within the
    CMS experiment. Note that while this tool was originally developed in the Higgs PAG, its usage
    is now widespread within CMS. Combine provides a command-line interface to many different statistical
    techniques, available inside RooFit/RooStats, that are used widely inside CMS.
  license:  Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  dev_url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit

extra:
  recipe-maintainers:
    - nsmith-
    - kcormi
    - anigamova
