# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 16 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "cms-combine" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 80216c792f4f5c2c32e47114f8b5f20d11b73d5bb95abed391b6dae407cee40e
  folder: HiggsAnalysis/CombinedLimit

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - pandas
    - pip
    - python<3.10  # due to root=6.22
    - root=6.22
    - boost
    - boost-cpp
    - root_base=6.22
    - eigen
    - vdt<0.4.4  # due to root=6.22
    - libcxx<12  # due to root=6.22

  run:
    - python

test:
  imports:
    - HiggsAnalysis.CombinedLimit.PhysicsModel
  commands:
    - combine -h
    - text2workspace.py -h

about:
  home: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  summary: 'A software tool used for statistical analysis within the CMS experiment'
  description: |
    Combine is a RooStats / RooFit - based software tool used for statistical analysis within the
    CMS experiment. Note that while this tool was originally developed in the Higgs PAG, its usage
    is now widespread within CMS. Combine provides a command-line interface to many different statistical
    techniques, available inside RooFit/RooStats, that are used widely inside CMS.
  license:  Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://cms-analysis.github.io/HiggsAnalysis-CombinedLimit/
  dev_url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit

extra:
  recipe-maintainers:
    - nsmith-
    - kcormi
    - anigamova
